apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../accelerators/nvidia

components:
  - ../../../components/multinode
  - ../../../components/monitoring

configMapGenerator:
  - name: model-config
    behavior: merge
    literals:
      - modelName=meta-llama/Llama-2-70b-hf
      - modelUri=hf://meta-llama/Llama-2-70b-hf
      - modelSize=200Gi

patches:
  # Configure decode LeaderWorkerSet
  - target:
      kind: LeaderWorkerSet
      name: modelservice-decode-lws
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/leaderWorkerTemplate/size
        value: 8
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/resources/limits/memory
        value: "80Gi"
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/resources/limits/cpu
        value: "32"
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/resources/requests/memory
        value: "80Gi"
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/resources/requests/cpu
        value: "32"
      - op: replace
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/1/value
        value: "4"