apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../accelerators/nvidia

components:
  - ../../../components/requester

configMapGenerator:
  - name: model-config
    behavior: merge
    literals:
      - modelName=gpt2
      - modelUri=hf://gpt2
      - modelSize=5Gi

patches:
  # Configure requester ReplicaSet
  - target:
      kind: ReplicaSet
      name: modelservice-decode-requester
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "2"