apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  # Enable prefill Deployment
  - target:
      kind: Deployment
      name: modelservice-prefill
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # Enable prefill LWS (for multinode prefill)
  # This will be overridden to 0 if multinode component isn't used
  - target:
      kind: LeaderWorkerSet
      name: modelservice-prefill-lws
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0