apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patches/decode-init-container.yaml
  - path: patches/prefill-init-container.yaml
  - path: patches/decode-lws-init-container.yaml
  - path: patches/prefill-lws-init-container.yaml