apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - decode-requester-replicaset.yaml

patches:
  # Disable regular decode deployment when using FMA requester
  - target:
      kind: Deployment
      name: modelservice-decode
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0