apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../accelerators/intel-xe

configMapGenerator:
  - name: model-config
    behavior: merge
    literals:
      - modelName=TinyLlama/TinyLlama-1.1B-Chat-v1.0
      - modelUri=hf://TinyLlama/TinyLlama-1.1B-Chat-v1.0
      - modelSize=10Gi

patches:
  # Enable decode deployment
  - target:
      kind: Deployment
      name: modelservice-decode
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "32Gi"
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "16"
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "32Gi"
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "16"